---

version: "3"

services:
  php:
    image: kanna5/privatebin
    build: ./images
    restart: unless-stopped
    volumes:
      - data:/usr/local/privatebin/data
      - ./conf.php:/usr/local/privatebin/cfg/conf.php:ro

  nginx:
    image: kanna5/privatebin
    build: ./images
    ports:
      - "8000:80"
    stop_signal: SIGQUIT
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]

volumes:
  data:
